name: 'DepGraph'

on:
  push:
    branches:
      - main

jobs:
  coverage:

    runs-on: [ubuntu-latest]
    name: Update dependencies graph

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Build and test with Maven
        run: mvn -V --color always -ntp clean verify -Dgpg.skip -Pdepgraph
      - name: Commit updated dependency graph
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add doc/dependency-graph.puml
          git commit -m "Update dependency graph to latest versions from POM" || true
      - name: Push updated dependency graph to GitHub repository
        uses: ad-m/github-push-action@master
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
